version: 0.9.0
project:
  name: ai-commander
  description: ''
  version: 0.9.0
editor:
  default: code
templates:
  directory: templates
tasks:
  directory: tickets
  auto_id: true
  id_format: TSK-{counter:04d}
git:
  auto_commit: false
  commit_prefix: '[ai-trackdown]'
plugins: {}
epics:
  counter: 6
issues:
  counter: 23
